### ISSUE TITLE
Bug while fetching balance of user

### ISSUE THREAD

**Issue by aman400** [citruspay/open-android-v3#15]
Method POST must have a request body

**Comment by MangeshKadam** [comment]
can you brief this problem. or share the error log..

**Comment by aman400** [comment]
07-21 13:29:42.572    1518-1518/com.grofers.customerapp D/CITRUSSDK﹕ ╔════════════════════════════════════════════════════════════════════════════════════════
07-21 13:29:42.578    1518-1518/com.grofers.customerapp D/CITRUSSDK﹕ ║ CitrusClient.init  (CitrusClient.java:136)
07-21 13:29:42.578    1518-1518/com.grofers.customerapp D/CITRUSSDK﹕ ║    CitrusClient.saveSDKEnvironment  (CitrusClient.java:167)
07-21 13:29:42.579    1518-1518/com.grofers.customerapp D/CITRUSSDK﹕ ╟────────────────────────────────────────────────────────────────────────────────────────
07-21 13:29:42.579    1518-1518/com.grofers.customerapp D/CITRUSSDK﹕ ║ PREVIOUS AND CURRENT ENVIRONMENT IS SAME
07-21 13:29:42.579    1518-1518/com.grofers.customerapp D/CITRUSSDK﹕ ╚════════════════════════════════════════════════════════════════════════════════════════
07-21 13:29:42.579    1518-1518/com.grofers.customerapp D/CITRUSSDK﹕ ╔════════════════════════════════════════════════════════════════════════════════════════
07-21 13:29:42.583    1518-1518/com.grofers.customerapp D/CITRUSSDK﹕ ║ ActivityPaymentOptions.onCitrusSelected  (ActivityPaymentOptions.java:1138)
07-21 13:29:42.583    1518-1518/com.grofers.customerapp D/CITRUSSDK﹕ ║    CitrusClient.init  (CitrusClient.java:157)
07-21 13:29:42.583    1518-1518/com.grofers.customerapp D/CITRUSSDK﹕ ╟────────────────────────────────────────────────────────────────────────────────────────
07-21 13:29:42.583    1518-1518/com.grofers.customerapp D/CITRUSSDK﹕ ║ VANITY*** grofers
07-21 13:29:42.583    1518-1518/com.grofers.customerapp D/CITRUSSDK﹕ ╚════════════════════════════════════════════════════════════════════════════════════════
07-21 13:29:42.606   1518-19319/com.grofers.customerapp D/Retrofit﹕ ---> HTTP GET https://admin.citruspay.com/utility/grofers/merchantName
07-21 13:29:42.606   1518-19319/com.grofers.customerapp D/Retrofit﹕ ---> END HTTP (no body)
07-21 13:29:42.689   1518-19325/com.grofers.customerapp D/Retrofit﹕ ---> HTTP POST https://admin.citruspay.com/service/v2/mycard/balance
07-21 13:29:42.689   1518-19325/com.grofers.customerapp D/Retrofit﹕ Authorization: Bearer 8ef81ba1-3aff-4634-9538-177fa153dc6a
07-21 13:29:42.690   1518-19325/com.grofers.customerapp D/Retrofit﹕ ---> END HTTP (no body)
07-21 13:29:42.690   1518-19325/com.grofers.customerapp D/Retrofit﹕ ---- ERROR https://admin.citruspay.com/service/v2/mycard/balance
07-21 13:29:42.690   1518-19325/com.grofers.customerapp D/Retrofit﹕ java.lang.IllegalArgumentException: method POST must have a request body.
            at com.squareup.okhttp.Request$Builder.method(Request.java:244)
            at retrofit.client.OkClient.createRequest(OkClient.java:59)
            at retrofit.client.OkClient.execute(OkClient.java:53)
            at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:326)
            at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220)
            at retrofit.RestAdapter$RestHandler$2.obtainResponse(RestAdapter.java:278)
            at retrofit.CallbackRunnable.run(CallbackRunnable.java:42)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at retrofit.Platform$Android$2$1.run(Platform.java:142)
            at java.lang.Thread.run(Thread.java:818)
07-21 13:29:42.690   1518-19325/com.grofers.customerapp D/Retrofit﹕ ---- END ERROR
07-21 13:29:43.057   1518-19319/com.grofers.customerapp D/Retrofit﹕ <--- HTTP 404 https://admin.citruspay.com/utility/grofers/merchantName (450ms)
07-21 13:29:43.057   1518-19319/com.grofers.customerapp D/Retrofit﹕ Date: Tue, 21 Jul 2015 07:59:43 GMT
07-21 13:29:43.057   1518-19319/com.grofers.customerapp D/Retrofit﹕ Server: Apache
07-21 13:29:43.057   1518-19319/com.grofers.customerapp D/Retrofit﹕ Cache-Control: no-cache,no-store,must-revalidate
07-21 13:29:43.057   1518-19319/com.grofers.customerapp D/Retrofit﹕ Expires: Thu, 01 Jan 1970 00:00:00 GMT
07-21 13:29:43.057   1518-19319/com.grofers.customerapp D/Retrofit﹕ Set-Cookie: JSESSIONID=AA5EFC49C8871753BB09D78EF8FF15C3.adminnode2; Path=/; Secure; HttpOnly
07-21 13:29:43.057   1518-19319/com.grofers.customerapp D/Retrofit﹕ Access-Control-Allow-Origin: *
07-21 13:29:43.057   1518-19319/com.grofers.customerapp D/Retrofit﹕ Access-Control-Allow-Methods: POST, GET, OPTIONS, DELETE, PUT
07-21 13:29:43.057   1518-19319/com.grofers.customerapp D/Retrofit﹕ Access-Control-Max-Age: 3600
07-21 13:29:43.064   1518-19319/com.grofers.customerapp D/Retrofit﹕ Access-Control-Allow-Headers: Authorization,Origin,X-Requested-With,Content-Type,Accept,merchantAccessKey,requestSignature
07-21 13:29:43.064   1518-19319/com.grofers.customerapp D/Retrofit﹕ Pragma: no-cache
07-21 13:29:43.064   1518-19319/com.grofers.customerapp D/Retrofit﹕ Cache-Control: pre-check=0,post-check=0
07-21 13:29:43.064   1518-19319/com.grofers.customerapp D/Retrofit﹕ Content-Language: en-US
07-21 13:29:43.064   1518-19319/com.grofers.customerapp D/Retrofit﹕ Vary: Accept-Encoding
07-21 13:29:43.064   1518-19319/com.grofers.customerapp D/Retrofit﹕ Keep-Alive: timeout=5, max=100
07-21 13:29:43.065   1518-19319/com.grofers.customerapp D/Retrofit﹕ Connection: Keep-Alive
07-21 13:29:43.065   1518-19319/com.grofers.customerapp D/Retrofit﹕ Transfer-Encoding: chunked
07-21 13:29:43.065   1518-19319/com.grofers.customerapp D/Retrofit﹕ Content-Type: text/html;charset=UTF-8
07-21 13:29:43.065   1518-19319/com.grofers.customerapp D/Retrofit﹕ OkHttp-Selected-Protocol: http/1.1
07-21 13:29:43.065   1518-19319/com.grofers.customerapp D/Retrofit﹕ OkHttp-Sent-Millis: 1437465582844
07-21 13:29:43.065   1518-19319/com.grofers.customerapp D/Retrofit﹕ OkHttp-Received-Millis: 1437465583056
07-21 13:29:43.072   1518-19319/com.grofers.customerapp D/Retrofit﹕ <?xml version="1.0" encoding="UTF-8"?>
    <!DOCTYPE HTML SYSTEM "about:legacy-compat">
    <html><head><title></title><link href="/resources/admin/images/favicon.ico" type="image/x-icon" rel="shortcut icon"/><link href="/resources/admin/css/default.css" type="text/css" rel="stylesheet"/></head><body class=""><div version="2.0"><meta content="SAMEORIGIN" http-equiv="X-FRAME-OPTIONS"/><script type="text/javascript">var NREUMQ=NREUMQ||[];NREUMQ.push(["mark","firstbyte",new Date().getTime()]);</script>
    <script>var ctx = ""</script><script>var buildVersion = "P1.21.0"</script><script>var buildNumber = "147"</script><div version="2.0"><div id="spinner"><img class="loader-img" alt="Loading..." src="/resources/admin/images/loader.gif"/></div><div id="mask"> </div></div><div id="page-header"><div class="page-wrap"><div class="logo-wrapper"><a href="http://www.citruspay.com"><img alt="Citrus" height="32" width="81" src="/resources/admin/images/logo_citrus-med.png"/></a></div><div class="login-wrapper clearfix"><ul class="login-menu"></ul></div><div class="clear"> </div></div><input value="http://www.citruspay.com" id="home_page_url" type="hidden"/></div></div><div id="page-wrapper"><div id="page-client-logo"> </div><div id="page-content"><div version="2.0"><div id="page-content"><div class="box-white fullerror"><h2>Requested Resource Not Found</h2><div class="hrsep"> </div><div class="transDetails">Sorry, we did not find the resource you were looking for.</div><div class="clear"/></div></div></div><div class="clear"> </div></div><div version="2.0" id="footer"><div id="page-footer"></div><script type="text/javascript">
    (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
    (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
    m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
    })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
    ga('create', 'UA-48950290-1',{'cookieDomain': 'none'});
    ga('send', 'pageview');
    </script><script type="text/javascript">if (!NREUMQ.f) { NREUMQ.f=function() {NREUMQ.push(["load",new Date().getTime()]);var e=document.createElement("script");e.type="text/javascript";e.src=(("http:"===document.location.protocol)?"http:":"https:") + "//" + "js-agent.newrelic.com/nr-100.js";document.body.appendChild(e);if(NREUMQ.a)NREUMQ.a();};NREUMQ.a=window.onload;window.onload=NREUMQ.f;};NREUMQ.push(["nrfj","bam.nr-data.net","f9e735f0ba","6266884","Z1ZXYkICV0pQV0cLDl4cf2VgTG58cxl6LCcfX1RPXxZNSh5ERgANWVBqXEMTQQ==",0,26,new Date().getTime(),"","","","",""]);</script>
    </div></div></body></html>
07-21 13:29:43.073   1518-19319/com.grofers.customerapp D/Retrofit﹕ <--- END HTTP (2640-byte body)
07-21 13:29:43.074    1518-1518/com.grofers.customerapp D/CITRUSSDK﹕ ╔════════════════════════════════════════════════════════════════════════════════════════
07-21 13:29:43.074    1518-1518/com.grofers.customerapp D/CITRUSSDK﹕ ║ CallbackRunnable$2.run  (CallbackRunnable.java:53)
07-21 13:29:43.074    1518-1518/com.grofers.customerapp D/CITRUSSDK﹕ ║    EventsManager$1.failure  (EventsManager.java:78)
07-21 13:29:43.074    1518-1518/com.grofers.customerapp D/CITRUSSDK﹕ ╟────────────────────────────────────────────────────────────────────────────────────────
07-21 13:29:43.074    1518-1518/com.grofers.customerapp D/CITRUSSDK﹕ ║ Failed to get Merchant name *****
07-21 13:29:43.075    1518-1518/com.grofers.customerapp D/CITRUSSDK﹕ ╚════════════════════════════════════════════════════════════════════════════════════════

**Comment by aman400** [comment]
This is what I am getting when I call following function:
citrusClient.getBalance(new Callback<Amount>()

**Comment by MangeshKadam** [comment]
Thanks Aman for the quick reply. We are looking into it. Will revert as soon as this issue is resolved.

**Comment by aman400** [comment]
and a message "Method POST must have a request body"

**Comment by salilgodbole** [comment]
Hi Aman,

We have fixed the issue. Please take the latest pull of the code.

**Comment by aman400** [comment]
Ok, Thanks.
