### ISSUE TITLE
Not able to fetch phone number of user from sdk

### ISSUE THREAD

**Issue by aman400** [citruspay/open-android-v3#16]
citrusClient.getUserMobileNumber() returns empty string

**Comment by MangeshKadam** [comment]
In case if you have not provided mobile number for Bind or SignIn you will empty String.

**Comment by aman400** [comment]
But signin method does not require any phone number to sign in.. where to pass phone number?

**Comment by aman400** [comment]
Moreover you are taking phone number during signing up of a user.. Why any person will enter his/her phone number as well as his email during sign in process?

**Comment by MangeshKadam** [comment]
yes.. thats why you are getting mobile number as empty String. Can you tell me why you need this mobile number?

**Comment by aman400** [comment]
I just need to show user the mobile number with which he signed up during signup process.
