### ISSUE TITLE
Why it use of salty-plateau-1529.herokuapp.com  what is that?

### ISSUE THREAD

**Issue by prashant31191** [citruspay/open-android-v3#36]
https://salty-plateau-1529.herokuapp.com/billGenerator.sandbox.php
or
https://salty-plateau-1529.herokuapp.com/billGenerator.sandbox.php?amount=555
i can use for the production it's write way?
https://salty-plateau-1529.herokuapp.com/billGenerator.production.php?amount=555

**Comment by salilgodbole** [comment]
This is the sample bill url for integration purpose.
You can use:
https://salty-plateau-1529.herokuapp.com/billGenerator.production.php url
for testing the integration on production environment.
But make sure to replace this with your bill url when you complete the
integration and move to production.

Also don't append amount to the url, SDK wil automatically append the
amount variable to the bill url.

Thanks,
*Salil Godbole*
Skype id: salilgodbole

**Comment by prashant31191** [comment]
Thank you @salilgodbole

**Comment by prashant31191** [comment]
how to get setupSignupSecret & setSigninSecret ?


when i use for the production then i remove "test-" ?
setupSignupId("signup");




this key getting from  https://sandboxadmin.citruspay.com/checkoutsettings/list#  right?
but there was only one secret key.


 Config.setupSignupId("test-signup");
        Config.setupSignupSecret("c78ec84e389814a05d3ae46546d16d2e786");

        Config.setSigninId("test-signin");
        Config.setSigninSecret("52f7e15efd4208cf5345dd554443fd99786");

**Comment by salilgodbole** [comment]
Hi Team,

Please help the merchant.

Thanks,
*Salil Godbole*
Skype id: salilgodbole

**Comment by prashant31191** [comment]
hi i get those key from the keystore.json file

Thank you.
